export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_CONTENTTYPES_START = 'FETCH_CONTENTTYPES_START';
export const FETCH_CONTENTTYPES_SUCCESS = 'FETCH_CONTENTTYPES_SUCCESS';
export const FETCH_CONTENTTYPES_FAIL = 'FETCH_CONTENTTYPES_FAIL';

export const FETCH_LIBRARY_START = 'FETCH_LIBRARY_START';
export const FETCH_LIBRARY_SUCCESS = 'FETCH_LIBRARY_SUCCESS';
export const FETCH_LIBRARY_FAIL = 'FETCH_LIBRARY_FAIL';

export const FETCH_ATTACHMENTTYPES_START = 'FETCH_ATTACHMENTTYPES_START';
export const FETCH_ATTACHMENTTYPES_SUCCESS = 'FETCH_ATTACHMENTTYPES_SUCCESS';
export const FETCH_ATTACHMENTTYPES_FAIL = 'FETCH_ATTACHMENTTYPES_FAIL';

export const FETCH_CONTENT_START = 'FETCH_CONTENT_START';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_FAIL = 'FETCH_CONTENT_FAIL';

export const LOAD_CONTENT_START = 'LOAD_CONTENT_START';
export const LOAD_CONTENT_SUCCESS = 'LOAD_CONTENT_SUCCESS';
export const LOAD_CONTENT_FAIL = 'LOAD_CONTENT_FAIL';

export const FETCH_CONTENTATTACHMENT_START = 'FETCH_CONTENTATTACHMENT_START';
export const FETCH_CONTENTATTACHMENT_SUCCESS = 'FETCH_CONTENTATTACHMENT_SUCCESS';
export const FETCH_CONTENTATTACHMENT_FAIL = 'FETCH_CONTENTATTACHMENT_FAIL';

export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

export const FETCH_LIBRARY_BOOKS_SUCCESS = 'FETCH_LIBRARY_BOOKS_SUCCESS';
export const FETCH_LIBRARY_BOOKS_START = 'FETCH_LIBRARY_BOOKS_START';
export const FETCH_LIBRARY_BOOKS_FAIL = 'FETCH_LIBRARY_BOOKS_FAIL';

export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_START = 'LOAD_BOOKS_START';
export const LOAD_BOOKS_FAIL = 'LOAD_BOOKS_FAIL';